---
editor_options: 
  markdown: 
    wrap: 72
---

#1 Load required packages

library(dplyr) library(ggplot2) library(tidyr)

#2 Load the dataset

setwd("C:/Users/dhara/GBC/R_Assignment_4066/") 
dataset <- read.csv("ds_salaries.csv")

#3 Print the structure of the dataset

str(dataset)

#4 List the variables in the dataset

variables \<- names(dataset) print(variables)

#5 Print the top 15 rows of the dataset

head(dataset, n=15)

#6 Making a dataframe

df_salaries \<- data.frame(dataset)

#7 User-defined function using a variable from the dataset

myFunction \<- function(df, var) { return(max(df[[var]])) }
myFunction(df_salaries, "salary_in_usd")

fun1 \<- function(df, var) { return(unique(df[[var]])) }
fun1(df_salaries, "job_title")

#8 Filter rows based on logical criteria

filtered_data \<- df_salaries %\>% filter(job_title == "Data Analyst",
company_size=="L") filtered_data

#9 Identify dependent and independent variables and create a new data frame

dependent_var \<- "salary" independent_vars \<- c("job_title",
"experience_level", "company_size")

dependent_df \<- df_salaries[c("salary", dependent_var)] independent_df
\<- df_salaries[c("salary", independent_vars)]

reshaped_df \<- reshape( independent_df, idvar = "id", varying =
list(independent_vars), v.names = "value", timevar = "variable", times =
independent_vars, direction = "long" )

merged_df \<- merge(dependent_df, reshaped_df, by = "salary")
print(merged_df)

#10 Remove missing values

dataset \<- na.omit(dataset)

#11 Identify and Remove duplicated data

duplicate_values \<- duplicated(dataset) duplicate_values dataset \<-
distinct(dataset)

#12 Reorder rows in descending order

dataset %\>% arrange(desc(salary) , desc(salary_in_usd))

#13 Rename column names

dataset \<- dataset %\>% rename(currency = salary_currency) dataset

#14 Add new variables using a mathematical function

dataset \<- dataset %\>% mutate(Biweekly_salary = salary / 26) dataset

#15 Create a training set using random number generator engine

set.seed(123) n_train \<- 3 train_indices \<-
sample(1:nrow(df_salaries), n_train) train_set \<-
df_salaries[train_indices, ] print(train_set)

#16 Summary statistics

summary(dataset)

#17 Statistical functions on numerical variables

mean_value \<-
mean(dataset$salary) median_value <- median(dataset$salary) mode_value
\<- table(dataset$salary)[which.max(table(dataset$salary))] range_value
\<- range(dataset\$salary)

print(paste0("mean: ", mean_value)) print(paste0("median: ",
median_value)) print(paste0("mode: ", mode_value)) print(paste0("range:
", range_value))

# Scatter plot

ggplot(dataset, aes(x = experience_level, y = salary)) + geom_point()+
labs(x = "Level of experience", y = "Salary", title = "Scatter Plot")

# Bar plot

ggplot(dataset, aes(x = company_size, fill = remote_ratio)) +
geom_bar(fill = "aquamarine4")+ labs(x = "Company Size", y = "Remote
ration", title = "Bar Plot")

# Correlation between two variables using linear regression

ggplot(dataset, aes(x = work_year, y = salary)) + geom_smooth(method =
"lm", se = FALSE) + labs(x = "Year", y = "Salary", title = "Linear
Regression Correlation Plot")
